// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessage.proto

package net.sz.game.test.proto;

public final class TestMessage {
  private TestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code net.sz.game.test.proto.Protos_Test}
   *
   * <pre>
   *消息约定
   * </pre>
   */
  public enum Protos_Test
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>test = 1001;</code>
     *
     * <pre>
     *测试消息，消息id
     * </pre>
     */
    test(0, 1001),
    ;

    /**
     * <code>test = 1001;</code>
     *
     * <pre>
     *测试消息，消息id
     * </pre>
     */
    public static final int test_VALUE = 1001;


    public final int getNumber() { return value; }

    public static Protos_Test valueOf(int value) {
      switch (value) {
        case 1001: return test;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protos_Test>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Protos_Test>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protos_Test>() {
            public Protos_Test findValueByNumber(int number) {
              return Protos_Test.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.sz.game.test.proto.TestMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protos_Test[] VALUES = values();

    public static Protos_Test valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Protos_Test(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:net.sz.game.test.proto.Protos_Test)
  }

  public interface ReqtestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    net.sz.game.test.proto.TestMessage.Protos_Test getMsgID();

    // optional string xxxx = 2;
    /**
     * <code>optional string xxxx = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    boolean hasXxxx();
    /**
     * <code>optional string xxxx = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    java.lang.String getXxxx();
    /**
     * <code>optional string xxxx = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getXxxxBytes();
  }
  /**
   * Protobuf type {@code net.sz.game.test.proto.ReqtestMessage}
   *
   * <pre>
   *客户端申请测试消息
   * </pre>
   */
  public static final class ReqtestMessage extends
      com.google.protobuf.GeneratedMessage
      implements ReqtestMessageOrBuilder {
    // Use ReqtestMessage.newBuilder() to construct.
    private ReqtestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqtestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqtestMessage defaultInstance;
    public static ReqtestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ReqtestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqtestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              net.sz.game.test.proto.TestMessage.Protos_Test value = net.sz.game.test.proto.TestMessage.Protos_Test.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              xxxx_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_ReqtestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_ReqtestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sz.game.test.proto.TestMessage.ReqtestMessage.class, net.sz.game.test.proto.TestMessage.ReqtestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqtestMessage> PARSER =
        new com.google.protobuf.AbstractParser<ReqtestMessage>() {
      public ReqtestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqtestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqtestMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];
    public static final int MSGID_FIELD_NUMBER = 1;
    private net.sz.game.test.proto.TestMessage.Protos_Test msgID_;
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    public net.sz.game.test.proto.TestMessage.Protos_Test getMsgID() {
      return msgID_;
    }

    // optional string xxxx = 2;
    public static final int XXXX_FIELD_NUMBER = 2;
    private java.lang.Object xxxx_;
    /**
     * <code>optional string xxxx = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public boolean hasXxxx() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string xxxx = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public java.lang.String getXxxx() {
      java.lang.Object ref = xxxx_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          xxxx_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string xxxx = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getXxxxBytes() {
      java.lang.Object ref = xxxx_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xxxx_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
      xxxx_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getXxxxBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getXxxxBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.test.proto.TestMessage.ReqtestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sz.game.test.proto.TestMessage.ReqtestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.sz.game.test.proto.ReqtestMessage}
     *
     * <pre>
     *客户端申请测试消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sz.game.test.proto.TestMessage.ReqtestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_ReqtestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_ReqtestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sz.game.test.proto.TestMessage.ReqtestMessage.class, net.sz.game.test.proto.TestMessage.ReqtestMessage.Builder.class);
      }

      // Construct using net.sz.game.test.proto.TestMessage.ReqtestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
        bitField0_ = (bitField0_ & ~0x00000001);
        xxxx_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_ReqtestMessage_descriptor;
      }

      public net.sz.game.test.proto.TestMessage.ReqtestMessage getDefaultInstanceForType() {
        return net.sz.game.test.proto.TestMessage.ReqtestMessage.getDefaultInstance();
      }

      public net.sz.game.test.proto.TestMessage.ReqtestMessage build() {
        net.sz.game.test.proto.TestMessage.ReqtestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.sz.game.test.proto.TestMessage.ReqtestMessage buildPartial() {
        net.sz.game.test.proto.TestMessage.ReqtestMessage result = new net.sz.game.test.proto.TestMessage.ReqtestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.xxxx_ = xxxx_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sz.game.test.proto.TestMessage.ReqtestMessage) {
          return mergeFrom((net.sz.game.test.proto.TestMessage.ReqtestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sz.game.test.proto.TestMessage.ReqtestMessage other) {
        if (other == net.sz.game.test.proto.TestMessage.ReqtestMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasXxxx()) {
          bitField0_ |= 0x00000002;
          xxxx_ = other.xxxx_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sz.game.test.proto.TestMessage.ReqtestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sz.game.test.proto.TestMessage.ReqtestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];
      private net.sz.game.test.proto.TestMessage.Protos_Test msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public net.sz.game.test.proto.TestMessage.Protos_Test getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public Builder setMsgID(net.sz.game.test.proto.TestMessage.Protos_Test value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
        onChanged();
        return this;
      }

      // optional string xxxx = 2;
      private java.lang.Object xxxx_ = "";
      /**
       * <code>optional string xxxx = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public boolean hasXxxx() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string xxxx = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public java.lang.String getXxxx() {
        java.lang.Object ref = xxxx_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          xxxx_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string xxxx = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getXxxxBytes() {
        java.lang.Object ref = xxxx_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          xxxx_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string xxxx = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder setXxxx(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        xxxx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string xxxx = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder clearXxxx() {
        bitField0_ = (bitField0_ & ~0x00000002);
        xxxx_ = getDefaultInstance().getXxxx();
        onChanged();
        return this;
      }
      /**
       * <code>optional string xxxx = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder setXxxxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        xxxx_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.sz.game.test.proto.ReqtestMessage)
    }

    static {
      defaultInstance = new ReqtestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.sz.game.test.proto.ReqtestMessage)
  }

  public interface RestestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    net.sz.game.test.proto.TestMessage.Protos_Test getMsgID();

    // optional string xxxx1 = 2;
    /**
     * <code>optional string xxxx1 = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    boolean hasXxxx1();
    /**
     * <code>optional string xxxx1 = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    java.lang.String getXxxx1();
    /**
     * <code>optional string xxxx1 = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getXxxx1Bytes();

    // optional string xxxx2 = 3;
    /**
     * <code>optional string xxxx2 = 3;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    boolean hasXxxx2();
    /**
     * <code>optional string xxxx2 = 3;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    java.lang.String getXxxx2();
    /**
     * <code>optional string xxxx2 = 3;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getXxxx2Bytes();
  }
  /**
   * Protobuf type {@code net.sz.game.test.proto.RestestMessage}
   *
   * <pre>
   *服务器回复测试消息
   * </pre>
   */
  public static final class RestestMessage extends
      com.google.protobuf.GeneratedMessage
      implements RestestMessageOrBuilder {
    // Use RestestMessage.newBuilder() to construct.
    private RestestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RestestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RestestMessage defaultInstance;
    public static RestestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RestestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RestestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              net.sz.game.test.proto.TestMessage.Protos_Test value = net.sz.game.test.proto.TestMessage.Protos_Test.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              xxxx1_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              xxxx2_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_RestestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_RestestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sz.game.test.proto.TestMessage.RestestMessage.class, net.sz.game.test.proto.TestMessage.RestestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RestestMessage> PARSER =
        new com.google.protobuf.AbstractParser<RestestMessage>() {
      public RestestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RestestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RestestMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];
    public static final int MSGID_FIELD_NUMBER = 1;
    private net.sz.game.test.proto.TestMessage.Protos_Test msgID_;
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
     */
    public net.sz.game.test.proto.TestMessage.Protos_Test getMsgID() {
      return msgID_;
    }

    // optional string xxxx1 = 2;
    public static final int XXXX1_FIELD_NUMBER = 2;
    private java.lang.Object xxxx1_;
    /**
     * <code>optional string xxxx1 = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public boolean hasXxxx1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string xxxx1 = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public java.lang.String getXxxx1() {
      java.lang.Object ref = xxxx1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          xxxx1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string xxxx1 = 2;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getXxxx1Bytes() {
      java.lang.Object ref = xxxx1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xxxx1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string xxxx2 = 3;
    public static final int XXXX2_FIELD_NUMBER = 3;
    private java.lang.Object xxxx2_;
    /**
     * <code>optional string xxxx2 = 3;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public boolean hasXxxx2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string xxxx2 = 3;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public java.lang.String getXxxx2() {
      java.lang.Object ref = xxxx2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          xxxx2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string xxxx2 = 3;</code>
     *
     * <pre>
     *附带消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getXxxx2Bytes() {
      java.lang.Object ref = xxxx2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xxxx2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
      xxxx1_ = "";
      xxxx2_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getXxxx1Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getXxxx2Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getXxxx1Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getXxxx2Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.test.proto.TestMessage.RestestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sz.game.test.proto.TestMessage.RestestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.sz.game.test.proto.RestestMessage}
     *
     * <pre>
     *服务器回复测试消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sz.game.test.proto.TestMessage.RestestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_RestestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_RestestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sz.game.test.proto.TestMessage.RestestMessage.class, net.sz.game.test.proto.TestMessage.RestestMessage.Builder.class);
      }

      // Construct using net.sz.game.test.proto.TestMessage.RestestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
        bitField0_ = (bitField0_ & ~0x00000001);
        xxxx1_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        xxxx2_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sz.game.test.proto.TestMessage.internal_static_net_sz_game_test_proto_RestestMessage_descriptor;
      }

      public net.sz.game.test.proto.TestMessage.RestestMessage getDefaultInstanceForType() {
        return net.sz.game.test.proto.TestMessage.RestestMessage.getDefaultInstance();
      }

      public net.sz.game.test.proto.TestMessage.RestestMessage build() {
        net.sz.game.test.proto.TestMessage.RestestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.sz.game.test.proto.TestMessage.RestestMessage buildPartial() {
        net.sz.game.test.proto.TestMessage.RestestMessage result = new net.sz.game.test.proto.TestMessage.RestestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.xxxx1_ = xxxx1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.xxxx2_ = xxxx2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sz.game.test.proto.TestMessage.RestestMessage) {
          return mergeFrom((net.sz.game.test.proto.TestMessage.RestestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sz.game.test.proto.TestMessage.RestestMessage other) {
        if (other == net.sz.game.test.proto.TestMessage.RestestMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasXxxx1()) {
          bitField0_ |= 0x00000002;
          xxxx1_ = other.xxxx1_;
          onChanged();
        }
        if (other.hasXxxx2()) {
          bitField0_ |= 0x00000004;
          xxxx2_ = other.xxxx2_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sz.game.test.proto.TestMessage.RestestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sz.game.test.proto.TestMessage.RestestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];
      private net.sz.game.test.proto.TestMessage.Protos_Test msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public net.sz.game.test.proto.TestMessage.Protos_Test getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public Builder setMsgID(net.sz.game.test.proto.TestMessage.Protos_Test value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .net.sz.game.test.proto.Protos_Test msgID = 1 [default = test];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = net.sz.game.test.proto.TestMessage.Protos_Test.test;
        onChanged();
        return this;
      }

      // optional string xxxx1 = 2;
      private java.lang.Object xxxx1_ = "";
      /**
       * <code>optional string xxxx1 = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public boolean hasXxxx1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string xxxx1 = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public java.lang.String getXxxx1() {
        java.lang.Object ref = xxxx1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          xxxx1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string xxxx1 = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getXxxx1Bytes() {
        java.lang.Object ref = xxxx1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          xxxx1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string xxxx1 = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder setXxxx1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        xxxx1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string xxxx1 = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder clearXxxx1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        xxxx1_ = getDefaultInstance().getXxxx1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string xxxx1 = 2;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder setXxxx1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        xxxx1_ = value;
        onChanged();
        return this;
      }

      // optional string xxxx2 = 3;
      private java.lang.Object xxxx2_ = "";
      /**
       * <code>optional string xxxx2 = 3;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public boolean hasXxxx2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string xxxx2 = 3;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public java.lang.String getXxxx2() {
        java.lang.Object ref = xxxx2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          xxxx2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string xxxx2 = 3;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getXxxx2Bytes() {
        java.lang.Object ref = xxxx2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          xxxx2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string xxxx2 = 3;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder setXxxx2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        xxxx2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string xxxx2 = 3;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder clearXxxx2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        xxxx2_ = getDefaultInstance().getXxxx2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string xxxx2 = 3;</code>
       *
       * <pre>
       *附带消息内容
       * </pre>
       */
      public Builder setXxxx2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        xxxx2_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.sz.game.test.proto.RestestMessage)
    }

    static {
      defaultInstance = new RestestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.sz.game.test.proto.RestestMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sz_game_test_proto_ReqtestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sz_game_test_proto_ReqtestMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sz_game_test_proto_RestestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sz_game_test_proto_RestestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TestMessage.proto\022\026net.sz.game.test.pr" +
      "oto\"X\n\016ReqtestMessage\0228\n\005msgID\030\001 \001(\0162#.n" +
      "et.sz.game.test.proto.Protos_Test:\004test\022" +
      "\014\n\004xxxx\030\002 \001(\t\"h\n\016RestestMessage\0228\n\005msgID" +
      "\030\001 \001(\0162#.net.sz.game.test.proto.Protos_T" +
      "est:\004test\022\r\n\005xxxx1\030\002 \001(\t\022\r\n\005xxxx2\030\003 \001(\t*" +
      "\030\n\013Protos_Test\022\t\n\004test\020\351\007"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_sz_game_test_proto_ReqtestMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_sz_game_test_proto_ReqtestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sz_game_test_proto_ReqtestMessage_descriptor,
              new java.lang.String[] { "MsgID", "Xxxx", });
          internal_static_net_sz_game_test_proto_RestestMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_sz_game_test_proto_RestestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sz_game_test_proto_RestestMessage_descriptor,
              new java.lang.String[] { "MsgID", "Xxxx1", "Xxxx2", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
